<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span class="logged-in" data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span class="not-logged-in" data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
            <?= $block->getBlockHtml('header.additional') ?>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <script>
        var promiseTRSANSG = (promiseThatResolvesAfterNSecondsGenerator = function(
            n = 0
        ) {
            return new Promise(function(resolve, reject) {
                setTimeout(function() {
                    resolve({
                        resolvedAfterNSeconds: n
                    });
                }, n * 1000);
            });
        });
        var promiseTRJANSG = (promiseThatRejectsAfterNSecondsGenerator = function(
            n = 0
        ) {
            return new Promise(function(resolve, reject) {
                setTimeout(function() {
                    reject({
                        rejectedAfterNSeconds: n
                    });
                }, n * 1000);
            });
        });
    </script>
    <?php break; ?>

    <?php case 'other': ?>
        <?= $block->getChildHtml() ?>
    <?php break; ?>

<?php endswitch; ?>
